### ISSUE TITLE
智障，写的都是什么乱七八糟的，哈哈

### ISSUE THREAD

**Issue by Deacon01** [gfw-breaker/banned-news1#5]
我吐了！

**Comment by yhnnd** [comment]
等共匪垮台等时候你更要吐了，脑残

**Comment by Deacon01** [comment]
> 残

那你加油哦！期待你功成那一天来打我。

**Comment by yhnnd** [comment]
> > 残
> 
> 那你加油哦！期待你功成那一天来打我。

共匪垮台和我有什么关系？他们垮台了怎么就等于我功成了？共匪垮台之后我要放鞭炮庆祝，我打你干什么？你以为我跟共匪的红卫兵和城管一样就喜欢打人？你配被我打吗？就你？你配吗？

**Comment by c6ForH66** [comment]
> > > 残
> > 
> > 
> > 那你加油哦！期待你功成那一天来打我。
> 
> 共匪垮台和我有什么关系？他们垮台了怎么就等于我功成了？共匪垮台之后我要放鞭炮庆祝，我打你干什么？你以为我跟共匪的红卫兵和城管一样就喜欢打人？你配被我打吗？就你？你配吗？

傻逼湾湾的脑残耗材

**Comment by yhnnd** [comment]
pinky go to hell. down with ccp
